# Generated by Django 5.2.7 on 2025-10-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_Bank', '0004_alter_profile_age_alter_profile_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='heamoglobin',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
