# Generated by Django 5.2.7 on 2025-10-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_Bank', '0006_profile_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(blank=True, max_length=20, null=True)),
                ('fullname', models.CharField(blank=True, max_length=40, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('health', models.CharField(blank=True, max_length=100, null=True)),
                ('heamoglobin', models.PositiveIntegerField(blank=True, null=True)),
                ('medications', models.CharField(blank=True, max_length=10, null=True)),
                ('tattoo', models.CharField(blank=True, max_length=10, null=True)),
                ('pregnancy', models.CharField(blank=True, max_length=10, null=True)),
                ('travel', models.CharField(blank=True, max_length=10, null=True)),
                ('lastDonation', models.DateField(blank=True, null=True)),
                ('is_first_time', models.BooleanField(default=False)),
                ('systolic', models.PositiveIntegerField(blank=True, null=True)),
                ('diastolic', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='diastolic',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='health',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='heamoglobin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_first_time',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lastDonation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='medications',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pregnancy',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='systolic',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tattoo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='travel',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='weight',
        ),
    ]
