# Generated by Django 5.2.7 on 2025-10-21 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_Bank', '0007_donor_remove_profile_address_remove_profile_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Blood_Bank.profile'),
        ),
    ]
