# Generated by Django 5.2.7 on 2025-10-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_Bank', '0008_donor_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='preferred_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
