# Generated by Django 5.2.7 on 2025-10-21 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_Bank', '0009_donor_preferred_date_donor_preferred_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Blood_Bank.profile'),
            preserve_default=False,
        ),
    ]
