# Generated by Django 5.2.7 on 2025-10-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_Bank', '0010_alter_donor_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(blank=True, max_length=40, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
