# Generated by Django 5.2.7 on 2025-10-22 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_Bank', '0011_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Blood_Bank.profile'),
            preserve_default=False,
        ),
    ]
