# Generated by Django 5.2.7 on 2025-10-23 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_Bank', '0012_hospital_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(blank=True, max_length=20, null=True)),
                ('patient_age', models.PositiveIntegerField(blank=True, null=True)),
                ('patient_dob', models.DateField(blank=True, null=True)),
                ('patient_gender', models.CharField(blank=True, max_length=10, null=True)),
                ('patient_number', models.CharField(blank=True, max_length=20, null=True)),
                ('patient_address', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Blood_Bank.profile')),
            ],
        ),
    ]
