# Generated by Django 5.2.7 on 2025-10-23 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_Bank', '0013_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood', models.CharField(blank=True, max_length=10, null=True)),
                ('unit', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=50, null=True)),
                ('urgency', models.BooleanField(default=False)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Blood_Bank.patient')),
            ],
        ),
    ]
