# Generated by Django 5.2.7 on 2025-10-23 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_Bank', '0014_request_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request_list',
            old_name='urgency',
            new_name='urgent',
        ),
    ]
