# Generated by Django 5.2.7 on 2025-10-23 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_Bank', '0015_rename_urgency_request_list_urgent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_list',
            name='blood',
        ),
        migrations.AddField(
            model_name='request_list',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='requested', max_length=10),
        ),
        migrations.AlterField(
            model_name='request_list',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blood_Bank.patient'),
        ),
    ]
