# Generated by Django 5.2.7 on 2025-10-25 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_Bank', '0016_remove_request_list_blood_request_list_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='diastolic',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='heamoglobin',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='preferred_date',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='preferred_time',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='systolic',
        ),
        migrations.CreateModel(
            name='Donation_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='requested', max_length=10)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blood_Bank.donor')),
            ],
        ),
    ]
