# Generated by Django 5.2.7 on 2025-10-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_Bank', '0018_hospital_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital_request',
            name='Blood_group',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
