# Generated by Django 5.2.7 on 2025-10-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_Bank', '0020_bloodstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_request',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('donated', 'Donated')], default='requested', max_length=10),
        ),
    ]
