# Generated by Django 5.2.7 on 2025-10-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_Bank', '0021_alter_donation_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation_request',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation_request',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
