# Generated by Django 5.2.7 on 2025-10-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_Bank', '0022_donation_request_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('donor', 'Donor'), ('patient', 'Patient'), ('hospital', 'Hospital')], default='donor', max_length=10),
        ),
    ]
