# Generated by Django 5.2.7 on 2025-10-30 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_Bank', '0023_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='travel',
        ),
    ]
