# Generated by Django 5.2.7 on 2025-10-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_Bank', '0024_remove_donor_travel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='a_neg',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='a_pos',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='ab_neg',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='ab_pos',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='b_neg',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='b_pos',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='o_neg',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='o_pos',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
