# Generated by Django 5.2.7 on 2025-10-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_Bank', '0025_hospital_a_neg_hospital_a_pos_hospital_ab_neg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital_request',
            name='patient_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='hospital_request',
            name='patient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='hospital_request',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
