# Generated by Django 5.2.7 on 2025-10-30 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_Bank', '0028_notification_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
    ]
