# Generated by Django 5.2.7 on 2025-10-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_Bank', '0029_remove_notification_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('hospital', 'Hospital'), ('donor', 'Donor'), ('patient', 'Patient')], max_length=10, null=True),
        ),
    ]
